### ISSUE TITLE
SubScope functionality while creating Webhooks

### ISSUE THREAD

**Issue by rammohanvarma** [smartsheet-platform/smartsheet-java-sdk#113]
Can't add subscope while creating webhooks? Is this feature yet to be added?

More details about this new feature can be found in below link.
https://developers.smartsheet.com/blog/introducing-webhooks-for-columns?utm_source=marketo&utm_medium=email&utm_campaign=release-webhooks_columns&mem=link&mkt_tok=eyJpIjoiTW1aak16UXdOakl5TkRRNSIsInQiOiJvaFQwTVRZTFwvd3E1dkl4ME9PckZhaVNIM2xMYjJZMEx2dk0zQjZZMTdTcVwvTGduNTZ4QTJsaVR6QzcyNlJYdnJlN1FPenh0eEttbWRJOGJ6cG1vbWEzY0F3YVwvVVpuUjloUU9uWjFGeWFuSUpcL0lqVm0xZGhnczZvV1VUS0Z0RnMifQ%3D%3D

**Comment by timwellswa** [comment]
This functionality was added in the 2.93.0 release.
