### ISSUE TITLE
getRows/getColumns on Sheet, retrieve null value

### ISSUE THREAD

**Issue by Tin-Nguyen** [smartsheet-platform/smartsheet-java-sdk#43]
hi,

I switched to use SmartSheet SDK version 2.0.2 for Java, however, I'm facing the issue that I cannot get all rows of sheet by `getRows`, the function returns `null` value.

**Comment by shiohigari** [comment]
Hi Tin, 
I am having the same issue. Did you ever find a solution?

**Comment by timboven** [comment]
I worked around this by retrieving a single sheet - If I load all sheets then no rows are returned.
If you however retrieve only a single sheet, then all details are populated

**Comment by seweil** [comment]
@timboven - Can you please share a repro case?

**Comment by NikitaZamalyutdinov** [comment]
@Tin-Nguyen 
 I faced with this issue too when tried to get sheets this way
'SmartsheetFactory.createDefaultClient(accessToken).sheetResources().listSheets()'
but, I solved it via 
```
...sheetResources().getSheet(
                sheetId, null, null, null, null, null, null, null
        )
``` 
Just load sheet via its ID.
