### ISSUE TITLE
SDK cannot apply format to cell

### ISSUE THREAD

**Issue by plsmartsheet** [smartsheet-platform/smartsheet-java-sdk#47]
Working WITH the JAVA SDK, I am not able to successfully submit a row change with formatting applied to a cell. I get the following error: "Unable to parse request. The following error occurred: Field \"format\" was of unexpected type.". However, a similar call made from the .NET SDK is successful. 
Note that the .Net SDK has the format as a string and Java SDK has the format object as a dictionary. Also note that if I omit the format from Java request, the call is successful.

**Comment by irwando** [comment]
Ancient issue.  Please reopen if there is an issue.
