### ISSUE TITLE
Clash With Android's Internal Apache HTTP

### ISSUE THREAD

**Issue by StillOnMyWay** [smartsheet-platform/smartsheet-java-sdk#55]
Hi All,

I'm currently trying to use this sdk in a simple application, but the version of HTTPCore and HTTPComponents being used is clashing with that of the android internal system on my phone. Now after numerous dependency ignores etc, I was able to avoid the clash, but then the version which I was left with either didn't have the new code (too **old** a version) or didn't have the old code (too **new**), of that which is in the SDK.

What I'm asking is do you plan to update the HTTP related code which you're using for this SDK to the newest of Apache HTTPClient 4.5.2?

**Comment by timwellswa** [comment]
This is not at all timely, but you can take a look at PR #102 and PR #105 regarding the use of the SDK on Android. Refer to the Android section in ADVANCED.md
